services:
  d-day-dashboard:
    build: .
    environment:
      - LOCAL_IP=${LOCAL_IP:-172.17.0.1}
      - API_PORT=3002
      - NEXT_PORT=3001
    ports:
      - "${NEXT_PORT:-3001}:3001"
      - "${API_PORT:-3002}:3002"
    restart: always
    volumes:
      - ./data.json:/app/data.json
